name: "GCC Warnings & Errors"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build_with_problem_matcher:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check Out Repo 
        uses: actions/checkout@v2
      -
        # For more complex builds, e.g. monorepos, build warnings may not contain the path from root.
        # This can interfere with annotation application.
        #
        # See the following resources for possible future fixes or alternatives.
        # - https://github.com/actions/toolkit/issues/480 <- excellent post by xt0rted
        # - https://github.com/microsoft/vscode-cpptools/issues/2266
        # - https://github.com/actions/toolkit/issues/480
        # - https://github.com/actions/runner/issues/659
        # - https://github.com/actions/runner/issues/765
        name: Load gcc-problem-matcher
        uses: electronjoe/gcc-problem-matcher@v1
      -
        name: build
        run: |
          g++ -Wall -Wextra src/main.cpp
          ./a.out
